exports.RELATIONSHIP_TO_AUTH_USER = {
  ME: "ME",
  UNKNOWN: "UNKNOWN",
  FRIEND: "FRIEND",
  SENDER: "SENDER",
  RECEVIER: "RECEVIER",
};

exports.RELATIONSHIP_STATUS = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
};
